-- Match Table
CREATE TABLE IF NOT EXISTS match (
    id TEXT PRIMARY KEY NOT NULL, -- uuid autogenerated at match creation
    start_time DATETIME NULL,
    end_time DATETIME NULL,
    version TEXT NOT NULL, -- Game (server) version
    type INTEGER NOT NULL, -- Define if a game is a private, public o random lobby game
    map_display TEXT NOT NULL -- JSON as TEXT
);

-- User/Player Table
CREATE TABLE IF NOT EXISTS player (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    new_password TEXT NULL, -- Used to store new password generated using password reset
    nickname TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    active INTEGER NOT NULL DEFAULT 1
);

-- Match Player Table
CREATE TABLE IF NOT EXISTS match_players (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    match TEXT NOT NULL,
    player INTEGER NOT NULL,
    character INTEGER NOT NULL, -- Reference of character in game assigned randomly at match start
    FOREIGN KEY (match) REFERENCES match(id),
    FOREIGN KEY (player) REFERENCES player(id)
);

-- Match Player's Objective Table
CREATE TABLE IF NOT EXISTS match_player_objetive (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    match_player INTEGER NOT NULL,
    character INTEGER NOT NULL,
    FOREIGN KEY (match_player) REFERENCES match_players(id)
);

-- Assassination Table
CREATE TABLE IF NOT EXISTS match_player_kill (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    match_player INTEGER NOT NULL,
    character INTEGER NOT NULL,
    points INTEGER NOT NULL,
    FOREIGN KEY (match_player) REFERENCES match_players(id)
);

-- Turn Table
CREATE TABLE IF NOT EXISTS turn (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    match_player INTEGER NOT NULL,
    order_num INTEGER NOT NULL,
    action1 INTEGER NULL,
    action1_info TEXT NULL, -- JSON as TEXT
    action2 INTEGER NULL,
    action2_info TEXT NULL, -- JSON as TEXT
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (match_player) REFERENCES match_players(id)
);

-- Indexes for performance improvement
CREATE INDEX IF NOT EXISTS idx_match_type ON match(type);
CREATE INDEX IF NOT EXISTS idx_match_players_match ON match_players(match);
CREATE INDEX IF NOT EXISTS idx_match_players_player ON match_players(player);
CREATE INDEX IF NOT EXISTS idx_turn_match_player ON turn(match_player);